# Generated by Django 3.2 on 2022-07-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220724_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statushistory',
            name='status_id',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status_history',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='StatusHistory',
        ),
    ]
