# Generated by Django 3.2 on 2022-07-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20220724_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Open'), (1, 'In progress'), (2, 'Review'), (3, 'Test'), (4, 'Done')], default=0, max_length=20),
        ),
    ]
