# Generated by Django 3.2 on 2022-07-24 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_status_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
        migrations.AddField(
            model_name='status',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'In progress'), (0, 'Open'), (2, 'Review'), (4, 'Done'), (3, 'Test')], default=0),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
