# Generated by Django 3.2 on 2022-07-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20220725_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('InProgress', 'In progress'), ('Review', 'Review'), ('Test', 'Test'), ('Done', 'Done')], default=0, max_length=20),
        ),
    ]
