# Generated by Django 3.2 on 2022-07-24 22:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0011_task_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('task', 'owner')},
        ),
    ]
