# Generated by Django 3.2 on 2022-07-24 23:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0012_alter_status_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('task', 'owner', 'status')},
        ),
    ]
