# Generated by Django 3.2 on 2022-07-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_alter_status_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('task', 'status')},
        ),
    ]
